apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: consumer-trigger-auth-aws-credentials
  namespace: keda
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     
    name: consumer-secret
    key: AWS_ACCESS_KEY_ID        
  - parameter: awsSecretAccessKey 
    name: consumer-secret
    key: AWS_SECRET_ACCESS_KEY   